### PR TITLE
issue #157

### PR DESCRIPTION
**Pull request by 4lovi4**
py3.8 tests added in ci according issue #157

### CODE REVIEW

**Comment by rmarkello** [comment]
Hey @4lovi4 ! This looks great—thank you so much! 🙌 

Worryingly, CircleCi _still_ isn't building for some reason. I've tried resetting it to see if so I'm going to play around and make some empty pushes to this branch to see if that will trigger it—apologies for the noisy notifications.

**Comment by rmarkello** [comment]
Ahh, I think I may have figured out what happened. From the [CircleCI docs](https://circleci.com/docs/2.0/oss/#build-pull-requests-from-forked-repositories):

> Note: If a user submits a pull request to your repository from a fork, but no pipeline is triggered, then the user most likely is following a project fork on their personal account rather than the project itself of CircleCi, causing the jobs to trigger under the user’s personal account and not the organization account. To resolve this issue, have the user unfollow their fork of the project on CircleCI and instead follow the source project. This will trigger their jobs to run under the organization when they submit pull requests

Could you unfollow your fork of `abagen` on CircleCI and instead follow the `rmarkello/abagen` project? Once you do that let me know and we can re-trigger a build on this PR.

Let me know if you have any questions!

**Comment by 4lovi4** [comment]
I've unfollowed my fork project in circleci. Unfortunately I can't find the way how to follow the original rmarkello/abagen. Maybe I have a lack of permissions. Didn't find this in ci doc also.

**Comment by rmarkello** [comment]
It looks like perhaps un-following was all you needed to do—the CircleCI is running (with the new Python 3.8 test build 🎉)!

The Azure error is unrelated to your changes here and I'm working on resolving it, so I'll merge this in if the CircleCI build passes :100:

**Comment by rmarkello** [comment]
As said, Azure failing is unrelated so I'm gonna go ahead and merge this. Thanks so much for adding Python 3.8 testing!!

**Pull request merged**
