### PR TITLE
Add mouse features

### PR DESCRIPTION
**Pull request by yingqiuz**
add mouse module, including:
(1) retrieve gene info, do gene id <->name/acronym conversions, check gene validity
(2) retrieve structure info, do structure id <->name/acronym conversions, check structure validity
(3) fetch unionisation data, including expression-energy, expression-density, sum-pixels, etc.

### CODE REVIEW

**Comment by rmarkello** [comment]
Hi @yingqiuz! :wave: Thank you so much for all this work! :raised_hands: 

Let me know when you think you'll be ready for a review&mdash;it looks like this PR is going to be a pretty sizable review so I don't want to do it preemptively if you'll be changing things around a lot.

Nonetheless, I'm wicked excited to see this functionality added to `abagen`!! :mouse:

**Comment by yingqiuz** [comment]
Hi @rmarkello thank you! I'll add another two tests.

**Comment by rmarkello** [comment]
Sounds great!

One thing that I would really appreciate before I review would be if you could remove any unnecessary files (like the `.idea` directory). I see you added it to the .gitignore file, but you'll need to `git rm` the files that had previously been added for this to take effect.

Other than that just let me know when you want me to dive in! :slightly_smiling_face:

**Comment by rmarkello** [comment]
Hi @yingqiuz ! It looks like the TravisCI is failing because of a dependency issue. I've updated the master branch to fix this so if you merging it into your PR that should fix the issue right up!

Let me know if you have any questions about how to do that! The first answer to this [StackOverflow question](https://stackoverflow.com/questions/16955980/git-merge-master-into-feature-branch) should do the trick :slightly_smiling_face:

**Comment by rmarkello** [comment]
Hi @yingqiuz ! I wanted to let you know that I haven't forgotten about this but I have just been super bogged down by other things. I will try and get to reviewing this soon ! Apologies for the delay, and thank you again for this awesome contribution :sparkles: :raised_hands:

**Comment by rmarkello** [comment]
The Travis is _definitely_ going to fail, but I'm working on refactoring some things and will address the tests as soon as I'm done!

**Comment by rmarkello** [comment]
The coverage decreased a bit, but the tests are passing! I'm going to go ahead and merge this in now, @yingqiuz. Thanks so much for your work!

**Pull request merged**
